### ISSUE TITLE
Settings > Privacy does not show updated as expected

### ISSUE THREAD

**Issue by thebeanieman** [pi-hole/web#1783]
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8 (Latest: v5.8)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) debian
- Platform:  Raspberry Pi

### Expected behavior
I visit the page Settings > Privacy (/admin/settings.php?tab=privacy)
The DNS resolver privacy level is set to Show everything and record everything
I change it to Anonymous mode and press Apply

The page should refresh and show the DNS resolver privacy level is set to Anonymous mode

### Actual behavior / bug

The page refreshes, a blue bar shows saying "Info - The privacy level has been increased" but the DNS resolver privacy level is still Show everything and record everything

When I manually refresh the page, the correct DNS resolver privacy level is showing.

The same happens in reverse.

### Steps to reproduce

As above

## Debug Token

- URL:  https://tricorder.pi-hole.net/am4g9pc59k

**Comment by yubiuser** [comment]
See the description in the linked PR for why this is a bug

**Comment by thebeanieman** [comment]
This is being worked on and seems very close to being resolved:
https://github.com/pi-hole/AdminLTE/pull/1911

I don't use github much, so sorry if I have made any mistakes.

**Comment by yubiuser** [comment]
Will be fixed by https://github.com/pi-hole/AdminLTE/pull/2130/commits/8cad8114cf68182b6202f20583da67b050e9c493

**Comment by lionralfs** [comment]
As this is fixed in #2130, I guess #1911 is obsolete and can be closed right?

**Comment by yubiuser** [comment]
Released with https://github.com/pi-hole/AdminLTE/releases/tag/v5.12

**Comment by thebeanieman** [comment]
Hello,

This is not fixed. Exactly the same error happens with Web Interface [v5.12].

Thanks,
David

**Comment by PromoFaux** [comment]
Confirmed -

![privacy](https://user-images.githubusercontent.com/1998970/164889829-a5022a01-4cf3-47a0-aa21-03d529a622b7.gif)

**Comment by thebeanieman** [comment]
Hey @PromoFaux,

Thank you for re-opening the issue and included a video showing the issue.

Thanks,
David

**Comment by yubiuser** [comment]
The issue was fixed by https://github.com/pi-hole/AdminLTE/commit/8cad8114cf68182b6202f20583da67b050e9c493, however, re-introduced by https://github.com/pi-hole/AdminLTE/pull/2126.

https://github.com/pi-hole/AdminLTE/pull/2183 should fix this now.

Please try it with

`pihole checkout web reload/privacy`

You can go back on track with `pihole checkout master` anytime (and before you want to upgrade to the next Pi-hole version)
