### ISSUE TITLE
pihole reconfigure fails (pihole -r)

### ISSUE THREAD

**Issue by Sassafras76** [pi-hole/web#1907]
### Versions
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is release v5.10.1 (Latest: v5.10.1)

### Platform

- OS and version:  raspiberry pi os  Linux 64 5.10.60-v8+ 
- Platform:  rapsberry pi 4

### Expected behavior

able to reconfigure pihole and remove ipv6 option

### Actual behavior / bug

  [✓] Detected AArch64 (64 Bit ARM) processor
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu not found
  [✗] FTL Engine not installed
pi@pihole64:~ $ https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu

### Steps to reproduce

pihole -r and chose options and on download it fails

## Debug Token

https://tricorder.pi-hole.net/PEqddHjS/

**Comment by yubiuser** [comment]
> all red backgrounds and the OK is only in green

This will be resolved by: https://github.com/pi-hole/AdminLTE/pull/1906

**Comment by Sassafras76** [comment]
> I don't think I'm understanding. You've unticked IPv6 and unchecked the IPv6 resolvers on the web interface. Is it still using IPv6 upstreams?

the check boxes used to be disabled when IPV6 was un-selected in the configure menu, and the reconfigure is not disabling the check boxes hence it is not removing IPV6 support 

i had IPV6 disabled until the last update, its now enabled and will not be disabled

**Comment by yubiuser** [comment]
The selection box (Select Protocol) is not necessary anymore. Since pi-hole/FTL#1111 and #4131 FTL handles the device's IP address interface-dependent. This means it is not necessary anymore to select which IP Pi-hole should guard. It will automatically block queries arriving on the current IPv4/IPv6 addresses. As part of this change the disable function was removed

https://github.com/pi-hole/AdminLTE/commit/cf917a6391a6a309be9dfdf87f0bde7c66d698b4#diff-4092c491c25e7e19aceafbe3c49d234ce7d1eca769519197d2ccba7bde75a27e

In fact, in the next version also the "Select Protocol" will be removed.
https://github.com/pi-hole/pi-hole/pull/4357

**Comment by Sassafras76** [comment]
> t IPv4/IPv6 addresses. As part o

i think I understand the approach but then need ot understand the choice when implemented.

will it just say "Cloudflare" or  and internally handle IPV4 or IPV6 or both if enabled?


![image](https://user-images.githubusercontent.com/89309860/135769767-4044bba0-5685-428c-8c87-3bc1670ea610.png)

**Comment by yubiuser** [comment]
You need to distinguish between Pi-hole receiving queries over IPv6 from clients and Pi-hole sending queries to IPv6 servers. Both are not the same. Additionally, also IPv4 servers can answer requests for `AAAA` queries (IPv6 addresses) without issues. So even if you have IPv6 network connectivity, a singel IPv4 upstream DNS server is enough (e.g. 8.8.8.8). 
That's the reason why there will be no "blending" between the IPv4/v6 checkboxes for the upstream DNS servers.

**Comment by Sassafras76** [comment]
does this account for when you want separate upstream servers for IPV4/V6?

how could I set google DNS for IPV4 and Cloudflare DNS for IPV6 if they get merged into one as suggested?

**Comment by yubiuser** [comment]
I'm not sure if I understand what you mean. 
You can select a Google DNS server with an IPV4 and a Cloudflare DNS with an IPv6 address. Queries (no matter if you request a `A` or `AAAA` record) will always sent only to one of the servers. Pi-hole has a mechanism to check which server responded faster in the past and will favor that one for a certain time. DNS is transparent to the underlying  IP protocol used to transport the data.

**Comment by yubiuser** [comment]
The mentioned bugs have been fixed.
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-11-web-v5-8-and-core-v5-6-released/50566

**Comment by Kuju29** [comment]
I'm still having the same issue.
![image](https://user-images.githubusercontent.com/22098092/138576152-fdc848ce-3084-47fa-ad07-329403c6a8e6.png)

**Comment by yubiuser** [comment]
@plan291037 

No, you don't. The original issue was a menu selection for IPv4/IPv6 blocking. Later the OP added the bug about the long-term data always displaying a red background even for permitted domains.
Your screenshot displays neither the long-term data nor is anything colored red. Pleas open a new issue..
