### ISSUE TITLE
development-v6 Local DNS errors

### ISSUE THREAD

**Issue by brightdroid** [pi-hole/web#2747]
### Versions
-  Pi-hole version is development-v6 6ae713e (Latest: v5.17.2)
-  web version is development-v6 6c3d45c (Latest: v5.20.2)
-  FTL version is development-v6 vDev-382469e (Latest: v5.23)

### Platform
- OS and version: Ubuntu 22.04.3
- Platform:  Docker 24.0.6

### Expected behavior

Add and delete "Local DNS records" without failure message.

### Actual behavior / bug

Blue Status with message is shown
> Error, something went wrong!
> undefined"

The Entry is added though!

Browser Network-Console shows this Status:

> (failed) net::ERR_EMPTY_RESPONSE

### Steps to reproduce

1. Go to 'Settings => Local DNS Records'
2. Click on 'Add new DNS record'
3. Enter DNS and IP
4. Click 'Add'
5. Blue Status message is shown

#### add record
![pihole6_add](https://github.com/pi-hole/web/assets/1255355/df615296-0c42-491f-b982-7ec82717d674)

#### delete record

![pihole6_del](https://github.com/pi-hole/web/assets/1255355/90943127-dd53-4284-9ebc-ceab7cdea412)

### Additional context

_Add any other context about the problem here._

**Comment by DL6ER** [comment]
Thanks for your report, https://github.com/pi-hole/FTL/pull/1698 should fix this

**Comment by brightdroid** [comment]
I still get the error when not reloading the page after creating an entry.

Tough, when you refresh the page after creating an entry, deleting works.

**Comment by yubiuser** [comment]
Please check with the latest version.

**Comment by brightdroid** [comment]
Problem solved for me, thanks.
