### ISSUE TITLE
Group Assignment for domains is displayed wrong

### ISSUE THREAD

**Issue by darkexplosiveqwx** [pi-hole/web#3394]
### Versions

- Pi-hole:  6.06
- AdminLTE:  6.1
- FTL:  6.1

### Platform

- OS and version:  aarch64 Raspberrypi OS 12

- Platform:  Pi 5

### Expected behavior

Show a normal dropdown for Group assignment

### Actual behavior / bug

Some weird dropdown or whatever this is:

https://github.com/user-attachments/assets/ffb07258-55ce-45e3-bfae-c95992e7dd4d

https://github.com/user-attachments/assets/8857da40-0feb-4f8a-8355-3599486d85e8

![Image](https://github.com/user-attachments/assets/b4d2c9bc-5daf-4147-9944-cb75f56c63bc)

This occurs on librewolf/Firefox Linux and on Firefox and safari iOS. Due to different resolution it looks a bit different on ios but the dropdown is as broken as on Linux. 

I am using ngnix reverse proxy to serve pihole at `/pihole/`
I have five groups: `Default`, `other one`, `one more goup`, `also a group` and `me too`.

I have another instance on another Pi where this issue does not occurs.

## Debug Token

- URL:  https://tricorder.pi-hole.net/D4rUmVoU/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

This looks fairly similar to a issue mentioned by @casperklein in [#3373](https://github.com/pi-hole/web/issues/3373#issuecomment-2790108152)

**Comment by rdwebdesign** [comment]
Sorry for the delay. This is not forgotten, but I couldn't test because I'm not using a reverse proxy and I didn't have time to configure a testing environment using a similar configuration.

It looks like some CSS is missing, resulting in elements using the wrong size/position.

Do you see any errors on the browser console (devtools)?

**Comment by darkexplosiveqwx** [comment]
When using librewolf I only get the warning of some fonts being blocked.
When using iOS Safari, Epiphany (Fedora)  and Chromium(Fedora) the issue also occurs and no Messages show up in the console, even when using the dropdown.

Selecting some CSS mode in Librewolf/Firefox dev tools shows:
```
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. icheck-bootstrap.min.css:5:1814
Elements matching selector: [class*="icheck-"] > input:first-child:disabled + input[type="hidden"] + label, [class*="icheck-"] > input:first-child:disabled + input[type="hidden"] + label::before, [class*="icheck-"] > input:first-child:disabled + label, [class*="icheck-"] > input:first-child:disabled + label::before
NodeList []


This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! domains
Error in parsing value for ‘max-height’.  Declaration dropped. 9 domains:1:1
```
The first message is very nested so only parts are displayed:
```
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. icheck-bootstrap.min.css:5:1814
Elements matching selector: [class*="icheck-"] > input:first-child:disabled + input[type="hidden"] + label, [class*="icheck-"] > input:first-child:disabled + input[type="hidden"] + label::before, [class*="icheck-"] > input:first-child:disabled + label, [class*="icheck-"] > input:first-child:disabled + label::before
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​​
constructor: function NodeList()
​​​
length: 0
​​​
name: "NodeList"
​​​
prototype: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​​​
<prototype>: function ()
​​
entries: function entries()
​​​
length: 0
​​​
name: "entries"
​​​
<prototype>: function ()
​​
forEach: function forEach()
​​​
length: 1
​​​
name: "forEach"
​​​
<prototype>: function ()
​​
item: function item()
​​​
length: 1
​​​
name: "item"
​​​
<prototype>: function ()
​​
keys: function keys()
​​​
length: 0
​​​
name: "keys"
​​​
<prototype>: function ()
​​
length: 
​​
values: function values()
​​​
length: 0
​​​
name: "values"
​​​
<prototype>: function ()
​​
Symbol(Symbol.iterator): function values()
​​​
length: 0
​​​
name: "values"
​​​
<prototype>: function ()
​​
Symbol(Symbol.toStringTag): "NodeList"
​​
<get length()>: function length()
​​​
length: 0
​​​
name: "get length"
​​​
<prototype>: function ()
​​
<prototype>: Object { … }
​​​
__defineGetter__: function __defineGetter__()
​​​​
length: 2
​​​​
name: "__defineGetter__"
​​​​
<prototype>: function ()
​​​
__defineSetter__: function __defineSetter__()
​​​​
length: 2
​​​​
name: "__defineSetter__"
​​​​
<prototype>: function ()
​​​
__lookupGetter__: function __lookupGetter__()
​​​​
length: 1
​​​​
name: "__lookupGetter__"
​​​​
<prototype>: function ()
​​​
__lookupSetter__: function __lookupSetter__()
​​​​
length: 1
​​​​
name: "__lookupSetter__"
​​​​
<prototype>: function ()
​​​
__proto__: 
​​​
constructor: function Object()
​​​​
assign: function assign()
​​​​
create: function create()
​​​​
defineProperties: function defineProperties()
​​​​
defineProperty: function defineProperty()
​​​​
entries: function entries()
​​​​
freeze: function freeze()
​​​​
fromEntries: function fromEntries()
​​​​
getOwnPropertyDescriptor: function getOwnPropertyDescriptor()
​​​​
getOwnPropertyDescriptors: function getOwnPropertyDescriptors()
​​​​
getOwnPropertyNames: function getOwnPropertyNames()
​​​​
getOwnPropertySymbols: function getOwnPropertySymbols()
​​​​
getPrototypeOf: function getPrototypeOf()
​​​​
groupBy: function groupBy()
​​​​
hasOwn: function hasOwn()
​​​​
is: function is()
​​​​
isExtensible: function isExtensible()
​​​​
isFrozen: function isFrozen()
​​​​
isSealed: function isSealed()
​​​​
keys: function keys()
​​​​
length: 1
​​​​
name: "Object"
​​​​
preventExtensions: function preventExtensions()
​​​​
prototype: Object { … }
​​​​
seal: function seal()
​​​​
setPrototypeOf: function setPrototypeOf()
​​​​
values: function values()
​​​​
<prototype>: function ()
​​​
hasOwnProperty: function hasOwnProperty()
​​​​
length: 1
​​​​
name: "hasOwnProperty"
​​​​
<prototype>: function ()
​​​
isPrototypeOf: function isPrototypeOf()
​​​​
length: 1
​​​​
name: "isPrototypeOf"
​​​​
<prototype>: function ()
​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​​
length: 1
​​​​
name: "propertyIsEnumerable"
​​​​
<prototype>: function ()
​​​
toLocaleString: function toLocaleString()
​​​​
length: 0
​​​​
name: "toLocaleString"
​​​​
<prototype>: function ()
​​​
toString: function toString()
​​​​
length: 0
​​​​
name: "toString"
​​​​
<prototype>: function ()
​​​
valueOf: function valueOf()
​​​​
length: 0
​​​​
name: "valueOf"
​​​​
<prototype>: function ()
​​​
<get __proto__()>: function __proto__()
​​​​
length: 0
​​​​
name: "get __proto__"
​​​​
<prototype>: function ()
​​​
<set __proto__()>: function __proto__()
​​​​
length: 1
​​​​
name: "set __proto__"
​​​​
<prototype>: function ()
```

![Image](https://github.com/user-attachments/assets/6c0190bf-ceb3-48bf-b53c-2408c4c6c155)

After some time additional messages appear:
```
Error in parsing value for ‘max-height’.  Declaration dropped. 9 domains:1:1
Error in parsing value for ‘max-height’.  Declaration dropped. 15 domains:1:1
Error in parsing value for ‘max-height’.  Declaration dropped. 12 domains:1:1
```

![Image](https://github.com/user-attachments/assets/82fd653e-6ed0-481b-ba35-f9c1863fedd2)
The currently open style is the result of clicking on the `domains:1:1` link in the console.

I hope this helps, I`m not that familiar with browsers rendering tho.

**Comment by rdwebdesign** [comment]
Thanks for the answer, but the errors from your Console tab are not related to the issues reported.

---

I was able to get a very similar page just disabling the CSS from `admin/vendor/bootstrap-select/bootstrap-select.min.css`.
Apparently your web interface is not loading `bootstrap-select.min.css` file, but I don't know why.

Just in case, if you are using any browser extensions, please disable them and check if something changes.

Also, please check if you see any issue on the Devtools *Network* tab? Are there 404 errors? Any other issues?

**Comment by rdwebdesign** [comment]
@darkexplosiveqwx 

Did you try the `development` branch? I think this is already fixed, but not released.

**Comment by darkexplosiveqwx** [comment]
I switched to `development` and this is still occurring.
Additionally the dropdowns on the Lists and Clients tab are not working as well (Im not sure if this is new or not, but I think this didn't happen on master).
Later I can check for potential issues in the browser console again.

**Comment by darkexplosiveqwx** [comment]
There is no occurrence of `bootstrap-select.min.css` in `view-source:https://my.site/pihole/admin/groups/lists` and it also does not show up in the network tab.
There is `<script src="/pihole/admin/vendor/bootstrap-select/bootstrap-select.min.js?v=1743281841"></script>`

`https://my.site/pihole/admin/vendor/bootstrap-select/bootstrap-select.min.css` does exist.

Full `view-source:https://my.site/pihole/admin/groups/lists`:
```
<!DOCTYPE html>
<!--
*  Pi-hole: A black hole for Internet advertisements
*  (c) 2017 Pi-hole, LLC (https://pi-hole.net)
*  Network-wide ad blocking via your own hardware.
*
*  This file is copyright under the latest version of the EUPL.
*  Please see LICENSE file for your rights under this license.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pi-hole blueberrypi</title>
    <meta name="csrf-token" content="dBuuM1p92WshAYj1VpOvZQ=">

    <link rel="apple-touch-icon" href="/pihole/admin/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/pihole/admin/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/pihole/admin/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/pihole/admin/img/favicons/manifest.json">
    <link rel="mask-icon" href="/pihole/admin/img/favicons/safari-pinned-tab.svg" color="#4488FF">
    <link rel="shortcut icon" href="/pihole/admin/img/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#4488FF">
    <meta name="msapplication-TileImage" content="/pihole/admin/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#4488FF">

    <!-- Theme fonts -->
    <link rel="stylesheet" href="/pihole/admin/vendor/fonts/ubuntu-mono/ubuntu-mono.css?v=1743366961">
    <link rel="stylesheet" href="/pihole/admin/vendor/fonts/antonio/antonio.css?v=1743366961">

    <style>
        html { background-color: #000; }
    </style>

    <!-- Common styles -->
    <link rel="stylesheet" href="/pihole/admin/vendor/bootstrap/css/bootstrap.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/icheck/icheck-bootstrap.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/animate/animate.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/bstreeview/bstreeview.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/font-awesome/css/all.min.css?v=1743366961">
    <link rel="stylesheet" href="/pihole/admin/vendor/nprogress/nprogress.min.css?v=1743281841">

    <link rel="stylesheet" href="/pihole/admin/vendor/datatables/datatables.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/datatables-buttons/datatables.buttons.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/datatables-select/datatables.select.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/daterangepicker/daterangepicker.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/bootstrap-toggle/bootstrap-toggle.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/waitMe-js/waitMe.min.css?v=1743366961">
    <link rel="stylesheet" href="/pihole/admin/vendor/select2/select2.min.css?v=1743281841">
    <link rel="stylesheet" href="/pihole/admin/vendor/adminLTE/AdminLTE.min.css?v=1743281841">

    <!-- Theme styles (lcars) -->
    <link rel="stylesheet" href="/pihole/admin/style/pi-hole.css?v=1746679224">
    <link rel="stylesheet" href="/pihole/admin/style/themes/lcars.css?v=1746679224">

    <noscript><link rel="stylesheet" href="/pihole/admin/vendor/js-warn/js-warn.css?v=1743281841"></noscript>

    <!-- scripts -->
    <script src="/pihole/admin/vendor/jquery/jquery.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/bootstrap/js/bootstrap.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/adminLTE/adminlte.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/bootstrap-notify/bootstrap-notify.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/waitMe-js/modernized-waitme-min.js?v=1743366961"></script>
    <script src="/pihole/admin/vendor/nprogress/nprogress.min.js?v=1743281841"></script>
    <script src="/pihole/admin/scripts/js/utils.js?v=1746679224"></script>
    <script src="/pihole/admin/vendor/select2/select2.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/datatables/datatables.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/datatables-select/datatables.select.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/datatables-buttons/datatables.buttons.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/chartjs/chart.umd.js?v=1746679224"></script>
    <script src="/pihole/admin/vendor/chartjs-plugin-deferred/chartjs-plugin-deferred.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/moment/moment.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/chartjs-adapter-moment/chartjs-adapter-moment.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/hammer/hammer.min.js?v=1743281841"></script> <!-- Needed for chartjs-plugin-zoom -->
    <script src="/pihole/admin/vendor/chartjs-plugin-zoom/chartjs-plugin-zoom.min.js?v=1743281841"></script>
    <script src="/pihole/admin/vendor/bstreeview/bstreeview.min.js?v=1743281841"></script>
    <script src="/pihole/admin/scripts/js/logout.js?v=1746679224"></script>
</head>
<body class="lcars hold-transition sidebar-mini layout-boxed logged-in" data-apiurl="/pihole/api" data-webhome="/pihole/admin/">
<noscript>
    <!-- JS Warning -->
    <div>
        <input type="checkbox" id="js-hide">
        <div class="js-warn" id="js-warn-exit"><h1>JavaScript Is Disabled</h1><p>JavaScript is required for the site to function.</p>
            <p>To learn how to enable JavaScript click <a href="https://www.enable-javascript.com/" rel="noopener" target="_blank">here</a></p><label for="js-hide">Close</label>
        </div>
    </div>
    <!-- /JS Warning -->
</noscript>

<!-- Send token to JS -->
<div id="enableTimer" hidden></div>
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/pihole/admin/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini">P<strong>h</strong></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">Pi-<strong>hole</strong></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <button class="sidebar-toggle-svg" data-toggle="push-menu" aria-label="Toggle Navigation">
                <i aria-hidden="true" class="fa fa-angle-double-left"></i>
                <span class="warning-count hidden" id="top-warning-count"></span>
            </button>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li>
                        <p class="navbar-text">
                            <span class="hidden-xs">hostname:</span>
                            <code>blueberrypi</code>
                        </p>
                    </li>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-bars"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img class="logo-img" src="/pihole/admin/img/logo.svg" alt="Pi-hole Logo" width="50" height="50">
                                <p>
                                    Open Source Ad Blocker
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body" id="advanced-info" style="display:none;"></li>
                            <!-- Menu Footer -->
                            <li class="user-footer">
                                <a class="btn-link" href="https://pi-hole.net/" rel="noopener" target="_blank">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentcolor" class="svg-inline--fa fa-fw menu-icon" viewBox="0 0 88.32 129.93">
  <path d="M36.56 39.93C20.34 38.2 4 25.94 2.71 0c25.17 0 38.63 14.9 39.93 38.51 4.76-28.32 27.07-25 27.07-25 1.06 16.05-12.12 25.78-27.07 26.59-4.2-8.85-29.36-30.56-29.36-30.56a.07.07 0 0 0-.11.08s24.28 21.15 23.39 30.31m7.6 90c-1.57-.09-16.22-.65-17.11-17.11-.72-10 7.18-17.37 7.18-27.08C32.44 61.53 0 64.53 0 85.74a19.94 19.94 0 0 0 5.83 14.14L30 124.06a19.94 19.94 0 0 0 14.14 5.83"/>
  <path d="M88.32 85.75c-.09 1.57-.65 16.22-17.11 17.11-10 .72-17.38-7.18-27.08-7.18-24.21 1.79-21.21 34.22 0 34.22a19.94 19.94 0 0 0 14.14-5.83L82.46 99.9a19.94 19.94 0 0 0 5.83-14.14"/>
  <path d="M44.16 41.59c1.57.09 16.22.65 17.11 17.11.72 10-7.18 17.37-7.18 27.08 1.79 24.21 34.22 21.21 34.22 0a19.94 19.94 0 0 0-5.83-14.14L58.3 47.45a19.94 19.94 0 0 0-14.14-5.83"/>
  <path d="M.08 85.75c.09-1.57.65-16.22 17.11-17.11 10-.72 17.38 7.18 27.08 7.18 24.21-1.82 21.21-34.22 0-34.22a19.94 19.94 0 0 0-14.14 5.83L5.94 71.61A19.94 19.94 0 0 0 .11 85.75"/>
</svg>
                                    Pi-hole Website
                                </a>
                                <hr>
                                <a class="btn-link" href="https://docs.pi-hole.net/" rel="noopener" target="_blank"><i class="fa-fw menu-icon fa-regular fa-circle-question"></i> Documentation</a>
                                <a class="btn-link" href="https://discourse.pi-hole.net/" rel="noopener" target="_blank"><i class="fa-fw menu-icon fab fa-discourse"></i> Pi-hole Discourse</a>
                                <a class="btn-link" href="https://github.com/pi-hole" rel="noopener" target="_blank"><i class="fa-fw menu-icon fab fa-github"></i> GitHub</a>
                                <a class="btn-link" href="https://discourse.pi-hole.net/c/announcements/5" rel="noopener" target="_blank"><i class="fa-fw menu-icon fa-solid fa-rocket"></i> Pi-hole Releases</a>
                                                                <a class="btn-link" href="#" id="logout-button"><i class="fa-fw menu-icon fa-solid fa-arrow-right-from-bracket"></i> Log out</a>
                                                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img class="logo-img" src="/pihole/admin/img/logo.svg" alt="Pi-hole logo" width="52" height="75">
                </div>
                <div class="pull-left info">
                    <p>Status</p>
                    <span id="status"></span><br>
                    <span id="query_frequency"></span><br>
                    <span id="cpu"></span><br>
                    <span id="memory"></span>
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header text-uppercase">Main</li>
                <!-- Home Page -->
                <li class="menu-main active">
                    <a href="/pihole/admin/">
                        <i class="fa fa-fw menu-icon fa-home"></i> <span>Dashboard</span>
                    </a>
                </li>
                <!-- Query Log -->
                <li class="menu-analysis">
                    <a href="/pihole/admin/queries">
                        <i class="fa fa-fw menu-icon fa-file-alt"></i> <span>Query Log</span>
                    </a>
                </li>

                <li class="header text-uppercase">Group Management</li>
                <!-- Group Management -->
                <li class="menu-group">
                    <a href="/pihole/admin/groups">
                        <i class="fa fa-fw menu-icon fa-user-friends"></i>
                        <span>Groups
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right" id="num_groups" title="Number of enabled groups"></span>
                            </span>
                        </span>
                    </a>
                </li>
                <li class="menu-group">
                    <a href="/pihole/admin/groups/clients">
                        <i class="fa fa-fw menu-icon fa-laptop"></i>
                        <span>Clients
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right" id="num_clients" title="Number of defined clients"></span>
                            </span>
                        </span>
                    </a>
                </li>
                <li class="menu-group">
                    <a href="/pihole/admin/groups/domains">
                        <i class="fa fa-fw menu-icon fa-list"></i>
                        <span>Domains
                            <span class="pull-right-container">
                                <span class="label bg-red pull-right" id="num_denied" title="Number of enabled deny rules (domains and regex)"></span>
                                <span class="label bg-green pull-right" id="num_allowed" title="Number of enabled allow rules (domains and regex)"></span>
                            </span>
                        </span>
                    </a>
                </li>
                <li class="menu-group">
                    <a href="/pihole/admin/groups/lists">
                        <i class="fa fa-fw menu-icon fa-shield-alt"></i>
                        <span>Lists
                            <span class="pull-right-container">
                                <span class="label bg-blue pull-right" id="num_lists" title="Number of subscribed and enabled lists"></span>
                                <span class="label bg-yellow pull-right" id="num_gravity" title="Total number of domains subscribed by your Pi-hole"></span>
                            </span>
                        </span>
                    </a>
                </li>

                <li class="header text-uppercase">DNS Control</li>
                <!-- Local DNS Records -->
                <!-- Enable/Disable Blocking -->
                <li id="pihole-disable" class="menu-dns treeview">
                    <a href="/pihole/admin/#">
                        <i class="fa fa-fw menu-icon fa-stop"></i> <span>Disable Blocking&nbsp;&nbsp;&nbsp;<span id="flip-status-disable"></span></span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="/pihole/admin/#" id="pihole-disable-indefinitely">
                                <i class="fa fa-fw menu-icon fa-infinity"></i> Indefinitely
                            </a>
                        </li>
                        <li>
                            <a href="/pihole/admin/#" id="pihole-disable-10s">
                                <i class="fa fa-fw menu-icon fa-clock"></i> For 10 seconds
                            </a>
                        </li>
                        <li>
                            <a href="/pihole/admin/#" id="pihole-disable-30s">
                                <i class="fa fa-fw menu-icon fa-clock"></i> For 30 seconds
                            </a>
                        </li>
                        <li>
                            <a href="/pihole/admin/#" id="pihole-disable-5m">
                                <i class="fa fa-fw menu-icon fas fa-clock"></i> For 5 minutes
                            </a>
                        </li>
                        <li>
                            <a href="/pihole/admin/#" id="pihole-disable-cst" data-toggle="modal" data-target="#customDisableModal">
                                <i class="fa fa-fw menu-icon fa-user-clock"></i> Custom time
                            </a>
                        </li>
                    </ul>
                    <!-- <a href="/pihole/admin/#" id="flip-status"><i class="fa fa-stop"></i> <span>Disable</span></a> -->
                </li>
                <li id="pihole-enable" class="menu-dns treeview" style="display: none;">
                    <a href="/pihole/admin/#">
                        <i class="fa fa-fw menu-icon fa-play"></i>
                        <span id="enableLabel">Enable Blocking&nbsp;&nbsp;&nbsp;
                            <span id="flip-status-enable"></span>
                        </span>
                    </a>
                </li>
                <li class="header text-uppercase">System</li>
                <!-- Settings -->
                <li class="menu-system treeview ">
                    <a href="/pihole/admin/#">
                        <i class="fa fa-fw menu-icon fa-cogs"></i> <span>Settings</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="">
                            <a href="/pihole/admin/settings/system">
                                <i class="fa-fw menu-icon fa-solid fa-circle-info"></i> <span>System</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/dns">
                                <i class="fa-fw menu-icon fa-solid fa-book-atlas"></i> <span>DNS</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/dhcp">
                                <i class="fa-fw menu-icon fa-solid fa-sitemap"></i> <span>DHCP</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/api">
                                <i class="fa-fw menu-icon fa-solid fa-window-restore"></i> <span>Web interface / API</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/privacy">
                                <i class="fa-fw menu-icon fa-solid fa-binoculars"></i> <span>Privacy</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/teleporter">
                                <i class="fa-fw menu-icon fa-solid fa-file-export"></i> <span>Teleporter</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="/pihole/admin/settings/dnsrecords">
                                <i class="fa-fw menu-icon fa-solid fa-address-book"></i> <span>Local DNS Records</span>
                            </a>
                        </li>
                        <li class=" settings-level-expert">
                            <a href="/pihole/admin/settings/all">
                                <i class="fa-fw menu-icon fa-solid fa-pen-to-square"></i> <span>All settings</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Tools -->
                <li class="menu-system treeview">
                    <a href="/pihole/admin/#">
                        <i class="fa fa-fw menu-icon fa-tools"></i> <span>Tools</span>
                        <span class="warning-count hidden"></span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <!-- Pi-hole diagnosis -->
                        <li class="">
                            <a href="/pihole/admin/messages">
                                <i class="fa fa-fw menu-icon fa-file-medical-alt"></i> <span>Pi-hole diagnosis</span>
                                <span class="pull-right-container warning-count hidden"></span>
                            </a>
                        </li>
                        <!-- Tail log files -->
                        <li class="treeview ">
                            <a href="/pihole/admin/#">
                                <i class="fa-fw menu-icon fa-solid fa-list-ul"></i> <span>Tail log files</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <!-- Tail pihole.log -->
                                <li class="">
                                    <a href="/pihole/admin/taillog?file=dnsmasq">
                                        <i class="fa-fw menu-icon fa-solid fa-list-ul"></i> pihole.log
                                    </a>
                                </li>
                                <!-- Tail FTL.log -->
                                <li class="">
                                    <a href="/pihole/admin/taillog?file=ftl">
                                        <i class="fa-fw menu-icon fa-solid fa-list-ul"></i> FTL.log
                                    </a>
                                </li>
                                <!-- Tail webserver.log -->
                                <li class="">
                                    <a href="/pihole/admin/taillog?file=webserver">
                                        <i class="fa-fw menu-icon fa-solid fa-list-ul"></i> webserver.log
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- Run gravity.sh -->
                        <li class="">
                            <a href="/pihole/admin/gravity">
                                <i class="fa fa-fw menu-icon fa-arrow-circle-down"></i> <span>Update Gravity</span>
                            </a>
                        </li>
                        <!-- Query Lists -->
                        <li class="">
                            <a href="/pihole/admin/search">
                                <i class="fa fa-fw menu-icon fa-search"></i> <span>Search Lists</span>
                            </a>
                        </li>
                        <!-- Interfaces -->
                        <li class="">
                            <a href="/pihole/admin/interfaces">
                                <i class="fa fa-fw menu-icon fa-wifi"></i> <span>Interfaces</span>
                            </a>
                        </li>
                        <!-- Network -->
                        <li class="">
                            <a href="/pihole/admin/network">
                                <i class="fa fa-fw menu-icon fa-network-wired"></i> <span>Network</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Donate button -->
                <li class="header text-uppercase">Donate</li>
                <li class="menu-donate">
                    <a href="https://pi-hole.net/donate/" rel="noopener" target="_blank">
                        <i class="fas fa-fw menu-icon fa-donate"></i> <span>Donate</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

<!-- Title -->
<div class="page-header">
    <h1>Subscribed lists group management</h1>
</div>

<!-- Domain Input -->
<div class="row">
    <div class="col-md-12">
        <div class="box" id="add-group">
            <!-- /.box-header -->
            <div class="box-header with-border">
                <h3 class="box-title">
                    Add a new subscribed list
                </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="new_address">Address:</label>
                        <input id="new_address" type="text" class="form-control" placeholder="URL" autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off">
                    </div>
                    <div class="form-group col-lg-3 col-md-6">
                        <label for="new_comment">Comment:</label>
                        <input id="new_comment" type="text" class="form-control" placeholder="List description (optional)">
                    </div>
                    <div class="form-group col-lg-3 col-md-6">
                        <label for="new_group">Group assignment:</label>
                        <div><select class="selectpicker form-control" id="new_group" multiple></select></div>
                    </div>
                </div>
            </div>
            <div class="box-footer clearfix">
                <strong>Hints:</strong>
                <ol>
                    <li>Please run <code>pihole -g</code> or update your gravity list <a href="/pihole/admin/gravity">online</a> after modifying your lists.</li>
                    <li>Multiple lists can be added by separating each <em>unique</em> URL with a space or comma</li>
                    <li>Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.</li>
                </ol>
                <div class="btn-toolbar pull-right" role="toolbar" aria-label="Toolbar with buttons">
                    <div class="btn-group" role="group">
                        <button type="button" id="btnAddBlock" class="btn btn-danger pull-right">Add blocklist</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" id="btnAddAllow" class="btn btn-success pull-right">Add allowlist</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box" id="lists-list">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Subscribed lists
                </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="listsTable" class="table table-striped table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th></th>
                            <th class="no-padding"></th>
                            <th class="no-padding"></th>
                            <th>Address</th>
                            <th>Status</th>
                            <th>Comment</th>
                            <th>Group assignment</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                </table>
                <button type="button" id="resetButton" class="btn btn-default btn-sm text-red hidden">Reset sorting</button>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

<script src="/pihole/admin/vendor/bootstrap-select/bootstrap-select.min.js?v=1743281841"></script>
<script src="/pihole/admin/vendor/bootstrap-toggle/bootstrap-toggle.min.js?v=1743281841"></script>
<script src="/pihole/admin/scripts/js/groups-common.js?v=1746679224"></script>
<script src="/pihole/admin/scripts/js/groups-lists.js?v=1746679224"></script>


        </section>
        <!-- /.content -->
    </div>
    <!-- Modal for custom disable time -->
    <div class="modal fade" id="customDisableModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Custom disable timeout</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <input id="customTimeout" class="form-control" type="number" value="60">
                        <div class="input-group-btn" data-toggle="buttons">
                            <label class="btn btn-default">
                                <input id="selSec" type="radio"> Secs
                            </label>
                            <label id="btnMins" class="btn btn-default active">
                                <input id="selMin" type="radio"> Mins
                            </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="pihole-disable-custom" class="btn btn-primary" data-dismiss="modal">Submit</button>
                </div>
            </div>
        </div>
    </div> <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="row row-centered text-center">
            <div class="col-xs-12 col-sm-6">
                <strong><a href="https://pi-hole.net/donate/" rel="noopener" target="_blank"><i class="fa fa-heart text-red"></i> Donate</a></strong> if you found this useful.
            </div>
        </div>

        <div class="row row-centered text-center version-info">
            <div class="col-xs-12 col-sm-12 col-md-10">
                <ul class="list-inline" id="versions"></ul>
                <p style="margin: 15px 0 0;" id="update-hint"></p>
            </div>
        </div>
    </footer>

</div>
<!-- ./wrapper -->
<script src="/pihole/admin/scripts/js/footer.js?v=1746679224"></script>

<div id="advanced-info-data" style="display: none;" data-starttime="69015.75663807" data-endtime="69015.758053443" data-client-ip="127.0.0.1" data-xff="MTkyLjE2OC4xNzguMTM4"></div>
</body>
</html>
```

**Comment by rdwebdesign** [comment]
This CSS file should be on the page. I can see it in my web interface.
<details><summary><i>Open for more details</i></summary>


This is how the "view-source" looks like in my machine:

![Image](https://github.com/user-attachments/assets/6f429645-f1e9-4237-946f-666a7dc12c55)

And devtools shows the file:

![Image](https://github.com/user-attachments/assets/571faa4e-0b48-4b3b-b289-6370db3c8246)
</details>

---

The only thing I can imagine is:
- the `scriptname` variable is not receiving the expected value when you use `webserver.paths.prefix`.
- Then, the following line fails and the file is not loaded:
  https://github.com/pi-hole/web/blob/1eaddca8db2e54a57e682633ea31096a3166b082/scripts/lua/header.lp#L89-L93

Can you please try to edit one file?

Open `/var/www/html/admin/scripts/lua/header_authenticated.lp` and add this code to the end of the file:
```php
<p>scriptname = <?= scriptname ?></p>
```

Then save it and reload the ***Lists*** page. You should see the result above the page title:

![Image](https://github.com/user-attachments/assets/2546720e-dc1d-46f0-a6c3-5c557095bcf9)

Do you see something different than `groups/lists`

**Comment by darkexplosiveqwx** [comment]
I followed your steps, on every tab it now shows `scriptname = index.lp`.
(Dashboard, Lists, Domains, Groups, Settings, etc.)

![Image](https://github.com/user-attachments/assets/01617623-d276-41ac-89e6-e1ad7a548f2d)

**Comment by rdwebdesign** [comment]
Then we confirmed this is exactly the same issue we are seeing on the other issue (3373).
This will need to be fixed in FTL.

Thanks for the debug.

**Comment by rdwebdesign** [comment]
@DL6ER 

The line below is not returning the expected value when `webserver.paths.prefix` is used:
https://github.com/pi-hole/web/blob/796d5922a60838af5d99fe6e90509f95ff697342/scripts/lua/header.lp#L17

`scriptname` always returns `index.lp`. 

I didn't test using a reverse proxy, but apparently `mg.request_info.request_uri` is not returning the path with the prefix.

**Comment by rdwebdesign** [comment]
@darkexplosiveqwx 

I think I found a solution without changing FTL code.

Can you please try `fix/scriptname_variable` branch?

`pihole checkout web fix/scriptname_variable`

**Comment by darkexplosiveqwx** [comment]
This seems to be working, the dropdown looks as expected, the script fits the page like `scriptname = groups/domains`

<img width="935" alt="Image" src="https://github.com/user-attachments/assets/de17ebe7-9e6f-48eb-8e9d-9db87f794b90" />
